making sure the build works before the remote server is erased

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -5,22 +5,39 @@ on:
     branches: [ master ]
 
 jobs:
-  build-and-deploy:
+  build:
     runs-on: ubuntu-latest
 
     steps:
+    - name: Checkout
+      uses: actions/checkout@v2
+
     - name: Setup Node.js environment
       uses: actions/setup-node@v2
       with:
         node-version: '16'
 
-    - name: Checkout
-      uses: actions/checkout@v2
-
     - name: Build React App
       run: |
         npm install
-        CI='' npm run build
+        npm run build
+
+    - name: Check Build
+      run: |
+        if [ -d "build" ]; then
+          echo "Build directory exists. Build successful."
+        else
+          echo "Build directory does not exist. Build failed."
+          exit 1
+        fi
+
+  deploy:
+    needs: build
+    runs-on: ubuntu-latest
+
+    steps:
+    - name: Checkout
+      uses: actions/checkout@v2
 
     - name: Clear html folder on remote
       uses: appleboy/ssh-action@master
